export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const SET_CATEGORIES = "SET_CATEGORIES"
export const ADD_CART= "ADD_CART"

export const UPDATE_CART = "UPDATE_CART"
export const UPDATE_QUANTITY = "UPDATE_QUANTITY"

export const DELETE_ITEM = "DELETE_ITEM"


export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"