import Head from "next/head";
import Layout from "../../components/Layout/Layout";
import SliderComponent from "../../components/Slider/Slider";
import Info from "../../components/Info/Info";
import Categories from "../../components/categories/Categories";
import AboutIndex from "../../components/AboutIndex/AboutIndex";
import axios from 'axios'
export default function Home() {
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <SliderComponent />

        <Info />
        <AboutIndex />
        <Categories />

   
      </Layout>
    </>
  );
}


// export async function getServerSideProps() {
//   const options = {
//     method: 'GET',
//     url: 'https://apidojo-hm-hennes-mauritz-v1.p.rapidapi.com/categories/list',
//     params: {lang: 'es', country: 'us'},
//     headers: {
//       'X-RapidAPI-Key': '0325c4a014msh19346b452589069p14ea52jsn340622083236',
//       'X-RapidAPI-Host': 'apidojo-hm-hennes-mauritz-v1.p.rapidapi.com'
//     }
//   };
  

//   try {
//     const response = await axios.request(options);
//     const data = response.data;
//     return { props: { data } };
//   } catch (error) {
//     console.error(error);
//     return { props: { data: null } };
//   }
// }
